SCREEN_WIDTH = 600
SCREEN_HEIGHT = 800

BRICKS_PER_ROW = 12
BRICKS_PER_COLUMN = 40
NUM_BRICK_ROWS = 6
BRICK_WIDTH = SCREEN_WIDTH / BRICKS_PER_ROW
BRICK_HEIGHT = SCREEN_HEIGHT / BRICKS_PER_COLUMN
